/*

 HELLOWORLD.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 2
   Tile set      : C:\Users\fubin\Desktop\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define helloWorldWidth 10
#define helloWorldHeight 2
#define helloWorldBank 0

unsigned char helloWorld[] =
{
  0x30,0x30,0x18,0x15,0x1C,0x1C,0x1F,0x30,0x30,0x30,
  0x30,0x30,0x27,0x1F,0x22,0x1C,0x14,0x30,0x30,0x30
};

/* End of HELLOWORLD.C */
